### ISSUE TITLE
crash with ImportFromEPSG

### ISSUE THREAD

**Issue by sgueniot** [QingMings/testgdal223#1]
Hello @QingMings , 
I have an issue when i try to ImportFromEPSG in a SpatialReference.
my code is 
```
        val src = SpatialReference()
        val tgt = SpatialReference()
        src.ImportFromEPSG(4326)
        tgt.ImportFromEPSG(2154)
        val transform = CoordinateTransformation(src, tgt)
        val easting=9.172643
        val northing= 42.577890
        val result = transform.TransformPoint(easting, northing)
        Log.d("Lambert93 = ","${result[0]};${result[1]}" )
```
the application crashes on the third line  src.ImportFromEPSG(4326) and  the error is : 
  Caused by: java.lang.RuntimeException: OGR Error: General Error
        at org.gdal.osr.osrJNI.SpatialReference_ImportFromEPSG(Native Method)
        at org.gdal.osr.SpatialReference.ImportFromEPSG(SpatialReference.java:565)

Working code in python is : 
```
from osgeo import osr
from osgeo import gdal
src = osr.SpatialReference()
tgt = osr.SpatialReference()
src.ImportFromEPSG(4326)
tgt.ImportFromEPSG(2154)
transform = osr.CoordinateTransformation(src, tgt)
easting=9.172643
northing= 42.577890
longitude, latitude, z = transform.TransformPoint(easting, northing)
print("Lambert93 = ",longitude,",",latitude )
```

Do you have an idea to fix my issue ?
Thanks

**Comment by QingMings** [comment]
@sgueniot   

Have you set the "GDAL_DATA" value?

```java
 gdal.SetConfigOption("GDAL_DATA","YOUR GDAL_DATA PATH")
```

**Comment by sgueniot** [comment]
Hello @QingMings ,
sorry, I didn't get a notification for your answer.
 I try this but, it's not working, i don't know why. with a getConfigOption, i can see that the config is done, but it's not working.
finally, i set  my path in an environment variable GDAL_DATA, and it's working. 

```
 private static void setGdalDataEnvironnementVariable(String dirPath){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            try {
                Os.setenv("GDAL_DATA",dirPath,true);
            } catch (ErrnoException e) {
                e.printStackTrace();
            }
        } else {
            try {
                Class < ? > libcore = Class.forName("libcore.io.Libcore");
                if (libcore == null) {
                    Log.w("GDAl", "Cannot find libcore.os.Libcore;");
                    //                return;
                } else {
                    final Object os = Class.forName("libcore.io.Libcore").getField("os").get(null);
                    Method method = os.getClass().getMethod("setenv", String.class, String.class, boolean.class);
                    method.invoke(os, "GDAL_DATA", dirPath, true);
                }
            } catch (Exception e) {
                Log.w("Sam1", Log.getStackTraceString(e));
                Log.w("Sam1", e.getMessage());
            }
        }
    }
```
